// generated by stringer -type=SteamApiMethod; DO NOT EDIT

package steam

import "fmt"

const _SteamApiMethod_name = "GetMatchHistoryGetMatchDetailsGetHeroesGetPlayerSummariesEconomySchemaGetLeagueListingGetLiveLeagueGamesGetMatchHistoryBySequenceNumGetTeamInfoByTeamID"

var _SteamApiMethod_index = [...]uint8{0, 15, 30, 39, 57, 70, 86, 104, 132, 151}

func (i SteamApiMethod) String() string {
	if i < 0 || i+1 >= SteamApiMethod(len(_SteamApiMethod_index)) {
		return fmt.Sprintf("SteamApiMethod(%d)", i)
	}
	return _SteamApiMethod_name[_SteamApiMethod_index[i]:_SteamApiMethod_index[i+1]]
}
